name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8.0.332+9
        cache: 'maven'
    - name: "[1/4] Compile project"
      run: mvn compile
    - name: "[2/4] Test project"
      run: mvn test
    - name: "[3/4] Static Analysis"
      run: mvn verify
    - name: "[4/4] Upload to Coveralls"
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: target/site/jacoco/jacoco.xml
